import importlib.util
import time
import traceback
import sys
import os
import subprocess
import tempfile
import numpy as np
from typing import Dict, Any, Tuple, Optional, List
from openevolve.evaluation_result import EvaluationResult

# ==========================================
# Unified Master Evaluator Template
# ==========================================
# This template incorporates best practices from 10+ production examples,
# including subprocess safety, multi-objective scoring, and self-healing.

def evaluate(program_path: str) -> EvaluationResult:
    """
    Example Evaluator for OpenEvolve.
    
    Args:
        program_path: Absolute path to the .py file generated by the LLM.
        
    Returns:
        EvaluationResult: An object containing 'metrics' (dict) and 'artifacts' (dict).
        The metrics MUST contain 'combined_score' (float) as the primary fitness signal.
    """
    
    # --- 1. CONFIGURATION & BASELINES ---
    # In production, you might load these from config.yaml
    TARGET_FUNCTION = "process_data"
    TIMEOUT_SECONDS = 10
    NUM_TRIALS = 3
    BASELINE_LATENCY = 0.05 # 50ms baseline example
    
    metrics = {
        "combined_score": 0.0,
        "correctness": 0.0,
        "speedup": 0.0,
        "reliability": 0.0,
        "execution_time": 0.0
    }
    artifacts = {
        "error_type": None,
        "error_message": None,
        "suggestion": None,
        "test_results": []
    }

    try:
        # --- 2. DYNAMIC LOADING & CONTRACT CHECK ---
        module_name = os.path.basename(program_path).replace(".py", "")
        spec = importlib.util.spec_from_file_location(module_name, program_path)
        program = importlib.util.module_from_spec(spec)
        
        try:
            spec.loader.exec_module(program)
        except Exception as e:
            artifacts.update({
                "error_type": "ImportError",
                "error_message": str(e),
                "suggestion": "Check for syntax errors or missing library imports."
            })
            return EvaluationResult(metrics=metrics, artifacts=artifacts)

        if not hasattr(program, TARGET_FUNCTION):
            artifacts.update({
                "error_type": "ContractError",
                "error_message": f"Required function '{TARGET_FUNCTION}' not found.",
                "suggestion": f"Your code must define 'def {TARGET_FUNCTION}(data):'."
            })
            return EvaluationResult(metrics=metrics, artifacts=artifacts)

        target_fn = getattr(program, TARGET_FUNCTION)

        # --- 3. EXECUTION & DATA PROCESSING ---
        test_cases = [
            {"input": [1, 2, 3], "expected": 6},
            {"input": [10, 20, 30], "expected": 60},
            {"input": [-1, 1], "expected": 0},
        ]

        total_latency = 0.0
        passed_count = 0
        
        for i, test in enumerate(test_cases):
            try:
                # Execution with high-resolution timer
                start_time = time.perf_counter()
                
                # IMPORTANT: For risky code, consider running in a separate Process/Subprocess
                result = target_fn(test["input"])
                
                latency = time.perf_counter() - start_time
                total_latency += latency

                # Correctness Check
                if result == test["expected"]:
                    passed_count += 1
                    artifacts["test_results"].append(f"Test {i}: PASSED ({latency:.4f}s)")
                else:
                    artifacts["test_results"].append(f"Test {i}: FAILED. Got {result}, Expected {test['expected']}")

            except Exception as e:
                artifacts["test_results"].append(f"Test {i}: CRASHED. {str(e)}")

        # --- 4. MULTI-OBJECTIVE METRIC CALCULATION ---
        # A. Correctness (0.0 - 1.0)
        metrics["correctness"] = passed_count / len(test_cases)
        
        # B. Efficiency / Speedup
        avg_latency = total_latency / len(test_cases) if len(test_cases) > 0 else 1.0
        metrics["execution_time"] = avg_latency
        metrics["speedup"] = BASELINE_LATENCY / max(avg_latency, 1e-9)
        
        # C. Reliability
        metrics["reliability"] = metrics["correctness"] # Simplified

        # --- 5. THE CRITICAL 'combined_score' (Fitness Function) ---
        # Formula: J = (Correctness * Weight1) + (Normalized_Efficiency * Weight2)
        # We only reward efficiency if the code is actually correct.
        if metrics["correctness"] > 0:
            # Normalize speedup to a 0-1 range for the score component
            efficiency_score = min(1.0, metrics["speedup"] / 2.0) 
            metrics["combined_score"] = (metrics["correctness"] * 0.7) + (efficiency_score * 0.3)
        else:
            metrics["combined_score"] = 0.0

        # Self-Healing Suggestions
        if metrics["combined_score"] < 1.0:
            if metrics["correctness"] < 1.0:
                artifacts["suggestion"] = "Focus on logic correctness first. Some test cases failed."
            else:
                artifacts["suggestion"] = "Solution is correct! Now try to reduce loop complexity for better speedup."

        return EvaluationResult(metrics=metrics, artifacts=artifacts)

    except Exception as e:
        # Ultimate fallback for engine stability
        artifacts.update({
            "error_type": "GlobalEvaluatorError",
            "error_message": str(e),
            "traceback": traceback.format_exc(),
            "suggestion": "The evaluator itself encountered an issue. Check input data types."
        })
        return EvaluationResult(metrics=metrics, artifacts=artifacts)

# --- Cascade Stages (Optional) ---
def evaluate_stage1(p): return evaluate(p) # Quick check
def evaluate_stage2(p): return evaluate(p) # Heavy check
