#!/usr/bin/env python3

import os
import sys
import urllib.request
from pathlib import Path
import subprocess

# Configuration
REPO_RAW_URL = "https://raw.githubusercontent.com/mdnaimul22/human-skills/main"
RULES_DIR = Path(".agents/rules")
FILES = [
    "coding-standards.md",
    "architecture-patterns.md",
    "maintenance-testing.md",
    "config-path-rules.md",
    "config-usage-rules.md",
    "project-config-example.md",
    "project-tree-example.md"
]

def check_empty_directory():
    """Safety Check: Ensure the directory is empty"""
    print("🚀 Starting Project Bootstrap...")
    items = os.listdir('.')
    if items:
        # Ignore hidden git dir if any, but let's be strict as bash was
        if items != ['.git']:
            print("⚠️  Error: This directory is not empty!")
            print("❌ Sorry, this module is for initializing new projects only. Running it in an existing project may result in data loss or configuration overwrite.")
            sys.exit(1)

def create_directories():
    """1. Create Directory Structure"""
    print("📁 Creating directories...")
    dirs = [
        "docs",
        "logs",
        "src/config",
        "src/core",
        "src/helpers",
        "src/providers",
        "src/schema",
        "src/services",
        "src/routers",
        "tests",
        str(RULES_DIR)
    ]
    
    for d in dirs:
        Path(d).mkdir(parents=True, exist_ok=True)
        print(f"   [Created] {d}")

def create_init_file(path_str: str, msg: str):
    path = Path(path_str)
    content = f'"""\n{msg}\n"""\n'
    path.write_text(content, encoding="utf-8")
    print(f"   [Created] {path_str}")

def create_init_files():
    """2. Create __init__.py files with conventions"""
    print("📄 Initializing Python packages with conventions...")
    
    create_init_file("src/__init__.py", "Global source package.")
    Path("src/requirements.txt").write_text("# write essential requirements with specific version compatibility\n")
    print("   [Created] src/requirements.txt")
    
    create_init_file("src/core/__init__.py", "Core business logic. Domain models and pure functional flows live here (Dont remove this Comments).")
    create_init_file("src/providers/__init__.py", "External service integrations (LLM, Database, API clients) only (Dont remove this Comments).")
    create_init_file("src/schema/__init__.py", "Single source of truth for Pydantic models and data structures. No business logic allowed (Dont remove this Comments).")
    create_init_file("src/services/__init__.py", "Fan-in point. Orchestrates Core logic and Providers. This is the only layer where Core and Providers converge to fulfill application-specific use cases. Business logic stays in Core, while Services handle the high-level orchestration (Dont remove this Comments).")
    create_init_file("src/routers/__init__.py", "Acts as the HTTP interface for the application services. No business logic allowed (Dont remove this Comments).")
    create_init_file("tests/__init__.py", "Test suite for the project.")

def create_base_files():
    """3. Create basic files"""
    print("📄 Creating base files...")
    
    gitignore_content = """# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*
.pnpm-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# Snowpack dependency directory (https://snowpack.dev/)
web_modules/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional stylelint cache
.stylelintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variable files
.env
.env.development.local
.env.test.local
.env.production.local
.env.local

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next
out

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and not Next.js
# https://nextjs.org/blog/next-9-1#public-directory-support
# public

# vuepress build output
.vuepress/dist

# vuepress v2.x temp and cache directory
.temp
.cache

# Docusaurus cache and generated files
.docusaurus

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# PNPM
pnpm-lock.yaml

# yarn v2
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*

# JetBrains
.idea

# Visual Studio Code 
*.code-workspace

# Environment and simulation data
.env
env

archived/

# Python
__pycache__/
*.py[cod]
*$py.class
"""
    Path(".gitignore").write_text(gitignore_content, encoding="utf-8")
    Path(".env").touch()
    Path(".env.example").write_text("# Environment Variables\n", encoding="utf-8")
    Path("main.py").write_text("print('Hello from Project Skeleton!')\n", encoding="utf-8")
    Path("README.md").write_text("# New Project\n", encoding="utf-8")
    
    license_content = """MIT License

Copyright (c) 2026 Naimul

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""
    Path("LICENSE").write_text(license_content, encoding="utf-8")
    
    print("   [Created] .gitignore, .env, .env.example, main.py, README.md, LICENSE")

def sync_rules():
    """4. Sync Rules"""
    print("📥 Syncing Rules from human-skills...")
    for filename in FILES:
        url = f"{REPO_RAW_URL}/.agents/rules/{filename}"
        dest = RULES_DIR / filename
        try:
            with urllib.request.urlopen(url) as response:
                content = response.read().decode("utf-8")
                dest.write_text(content, encoding="utf-8")
            print(f"   [Synced] {filename}")
        except Exception as e:
            print(f"   [Failed] {filename} - {e}")

def scaffold_human_skills():
    """5. Scaffold config and helpers via human-skills"""
    print("🤖 Integrating human-skills scaffolding tools...")
    
    # Run setconfig
    try:
        print("   [Running] setconfig...")
        subprocess.run(
            ["human-skills", '{"tool_name": "setconfig", "tool_args": {"destination": "src/config"}}'], 
            check=True, 
            stdout=subprocess.DEVNULL, 
            stderr=subprocess.DEVNULL
        )
        print("   ✅ scaffolded src/config/")
    except subprocess.CalledProcessError:
        print("   ❌ Failed to scaffold config layer (is human-skills installed globally?)")
    except FileNotFoundError:
        print("   ❌ human-skills command not found. Skipping auto-scaffold.")

    # Run sethelpers
    try:
        print("   [Running] sethelpers...")
        subprocess.run(
            ["human-skills", '{"tool_name": "sethelpers", "tool_args": {"destination": "src/helpers"}}'], 
            check=True, 
            stdout=subprocess.DEVNULL, 
            stderr=subprocess.DEVNULL
        )
        print("   ✅ scaffolded src/helpers/")
    except subprocess.CalledProcessError:
        print("   ❌ Failed to scaffold helpers layer.")
    except FileNotFoundError:
        pass

def main():
    check_empty_directory()
    create_directories()
    create_init_files()
    create_base_files()
    sync_rules()
    scaffold_human_skills()
    
    print("\n✨ Project Bootstrap Completed Successfully!")
    print("Happy Coding! 🎯")

if __name__ == "__main__":
    main()
