#!/bin/bash

# Configuration
REPO_RAW_URL="https://raw.githubusercontent.com/mdnaimul22/human-skills/main"
RULES_DIR=".agents/rules"
RULES_FILES=("coding_standareds.md" "project_config_example.md" "project_tree_example.md")

echo "🚀 Starting Project Bootstrap..."

# Safety Check: Ensure the directory is empty
if [ "$(ls -A)" ]; then
    echo -e "⚠️  Error: This directory is not empty!"
    echo "❌ Sorry, this module is for initializing new projects only. Running it in an existing project may result in data loss or configuration overwrite."
    exit 1
fi

# 1. Create Directory Structure
echo "📁 Creating directories..."
DIRS=(
    "docs"
    "logs"
    "src/configs"
    "src/core"
    "src/helpers"
    "src/providers"
    "src/schema"
    "src/services"
    "src/routers"
    "tests"
    "$RULES_DIR"
)

for dir in "${DIRS[@]}"; do
    mkdir -p "$dir"
    echo "   [Created] $dir"
done

# 2. Create __init__.py files with conventions
echo "📄 Initializing Python packages with conventions..."

function create_init() {
    local file=$1
    local msg=$2
    echo -e "\"\"\"\n$msg\n\"\"\"" > "$file"
    echo "   [Created] $file"
}

create_init "src/__init__.py" "Global source package."
create_init "src/configs/__init__.py" "All environment settings must be aggregated here and exposed via a Single Source of Truth."
create_init "src/core/__init__.py" "Core business logic. Domain models and pure functional flows live here."
create_init "src/helpers/__init__.py" "Global utilities and stateless helpers used across the entire project."
create_init "src/providers/__init__.py" "External service integrations (LLM, Database, API clients) only."
create_init "src/schema/__init__.py" "Single source of truth for Pydantic models and data structures. No business logic allowed."
create_init "src/services/__init__.py" "Fan-in point. Orchestrates Core logic and Providers. This is the only layer where Core and Providers converge to fulfill application-specific use cases. Business logic stays in Core, while Services handle the high-level orchestration."
create_init "src/routers/__init__.py" "Acts as the HTTP interface for the application services. No business logic allowed."
create_init "tests/__init__.py" "Test suite for the project."

# 3. Create basic files
echo "📄 Creating base files..."
cat <<EOF > .gitignore
# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*
.pnpm-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# Snowpack dependency directory (https://snowpack.dev/)
web_modules/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional stylelint cache
.stylelintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variable files
.env
.env.development.local
.env.test.local
.env.production.local
.env.local

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next
out

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and not Next.js
# https://nextjs.org/blog/next-9-1#public-directory-support
# public

# vuepress build output
.vuepress/dist

# vuepress v2.x temp and cache directory
.temp
.cache

# Docusaurus cache and generated files
.docusaurus

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# PNPM
pnpm-lock.yaml

# yarn v2
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*

# JetBrains
.idea

# Visual Studio Code 
*.code-workspace

# Environment and simulation data
.env
env

archived/

# Python
__pycache__/
*.py[cod]
*\$py.class
EOF

touch .env
echo "# Environment Variables" > .env.example
echo "print('Hello from Project Skeleton!')" > main.py
echo "# New Project" > README.md

cat <<EOF > LICENSE
MIT License

Copyright (c) 2026 Naimul

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
EOF

echo "   [Created] .gitignore, .env, .env.example, main.py, README.md, LICENSE"

# 4. Sync Rules
echo "📥 Syncing Rules from human-skills..."
for FILE in "${RULES_FILES[@]}"; do
    curl -sSL "$REPO_RAW_URL/.agents/rules/$FILE" -o "$RULES_DIR/$FILE"
    if [ $? -eq 0 ]; then
        echo "   [Synced] $FILE"
    else
        echo "   [Failed] $FILE"
    fi
done

echo -e "\n✨ Project Bootstrap Completed Successfully!"
echo "Happy Coding! 🎯"
